sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t mdrafiqsa/docker-react -f Dockerfile.dev .

script:
  - docker run mdrafiqsa/docker-react npm run test -- --coverage
